### PR TITLE
Update SkillHandler.cs

### PR DESCRIPTION
**Pull request by d3bug1**
This fixes the bounty-/waypointmap problem thx to  d2k2

### CODE REVIEW

**Comment by ne0ark** [comment]
This change causes this issue: http://d3helper.freeforums.net/post/1878. Without this patch things are working perfectly.

**Comment by d2k2-git** [comment]
@ne0ark A_Collection.Me.HeroStates.isTeleporting is not set correctly probably. without the fix d3helper stops working after open the bountymap

**Comment by Enigma32** [comment]
Oh didn't see this issue here. I already fixed it with 1e9fed1898baebf19dc7057441b6c6a97dd94064, saw the conditions were already checked in the large groups of conditions, so removed the special case entirely.

But is this fix bad? Would it go good by fixing isTeleporting?

**Comment by d2k2-git** [comment]
@Enigma32 your fix is ok.

when you rightclick on player portrait and click "teleport to player" , isTeleport is not set true.
we must fix this here instead:

```
private static void get_isTeleporting()
        {
            try
            {
                lock(A_Collection.Me.HeroGlobals.LocalPlayerData)
                {
                    switch (A_Collection.Me.HeroGlobals.LocalPlayerData.GetPowerCast())
                    {
                        case A_Enums.Powers.UseStoneOfRecall:
                        case A_Enums.Powers.UseDungeonStoneOfRecall:
                        case A_Enums.Powers.TeleportToWaypoint:
                        case A_Enums.Powers.TeleportToPlayer_1:
                        case A_Enums.Powers.TeleportToPlayer_2:


                            lock (A_Handler.Log.Exception.HandlerLog) A_Handler.Log.Exception.HandlerLog.Add(new A_Handler.Log.LogEntry(DateTime.Now, "isTeleporting -> true"));

                            A_Collection.Me.HeroStates.isTeleporting = true;
                            break;

                        default:
                            
                            A_Collection.Me.HeroStates.isTeleporting = false;
                            break;
                    }
                }
            }
```

**Comment by Enigma32** [comment]
Alright, I'll see what's going on with that.

**Comment by Enigma32** [comment]
I actually can't see anything in PlayerData indicating player is teleporting to another player. And that's when I diff the entire structure every 1ms.

**Comment by d2k2-git** [comment]
GetPowerCast() returns -1 when teleporting to a waypoint or another player. so maybe the flag is set somewhere else in this patch :S weird.

teleport to town (UseStoneOfRecall) is detected correctly

**Pull request closed without merging**
